import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/componants/shared/Navbar";
import Footer from "@/componants/shared/Footer";
import NextThemeProvider from "@/providers/NextThemeProvider";
import { Toaster } from "react-hot-toast";
import { ToastContainer } from "react-toastify/unstyled";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased bg-background text-foreground`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <NextThemeProvider>
         <Navbar/>
        <main>
          {children}
        </main>
          <Footer />
          <Toaster />
                 <ToastContainer />
       </NextThemeProvider>
      </body>
    </html>
  );
}
